[package]
name = "fft"
version = "0.1.0"
edition = "2024"

[dependencies]
num-complex = "0.4.6"
num-traits = "0.2.19"

[dev-dependencies]
criterion = "0.7.0"
rand = "0.8"
rustfft = "6.4.1"


[[bench]]
name = "bench"
harness = false
